## Working with Missing Data in Pandas

In [1]:
import numpy as np
import pandas as pd

from pandas import DataFrame

### Filling missing values using fillna(), replace() and interpolate()

In [3]:
data = {'name' : ['steve', 'john', 'mike', 'susan', 'jane', 'lisa', 'messi'],
        'age' : [20, 22, 21, 23, 22, 20, 21], 
        'gender' : ['male', 'male', 'male', 'female', 'female', 'female', 'male'],
        'rank' : [2, 1, 4, 5, 3, 6, 7]}
rank_df = DataFrame(data)
rank_df.iloc[2:5,1] = np.nan
rank_df.iloc[3:6,3] = np.nan
rank_df.iloc[3,:] = np.nan
rank_df

    name   age  gender  rank
0  steve  20.0    male   2.0
1   john  22.0    male   1.0
2   mike   NaN    male   4.0
3    NaN   NaN     NaN   NaN
4   jane   NaN  female   NaN
5   lisa  20.0  female   NaN
6  messi  21.0    male   7.0

In [4]:
rank_df.isnull()

    name    age  gender   rank
0  False  False   False  False
1  False  False   False  False
2  False   True   False  False
3   True   True    True   True
4  False   True   False   True
5  False  False   False   True
6  False  False   False  False

In [5]:
rank_df.notnull()

    name    age  gender   rank
0   True   True    True   True
1   True   True    True   True
2   True  False    True   True
3  False  False   False  False
4   True  False    True  False
5   True   True    True  False
6   True   True    True   True

In [6]:
bool_series = pd.isnull(rank_df["age"])
rank_df[bool_series]

   name  age  gender  rank
2  mike  NaN    male   4.0
3   NaN  NaN     NaN   NaN
4  jane  NaN  female   NaN

In [7]:
rank_df.fillna(0)

    name   age  gender  rank
0  steve  20.0    male   2.0
1   john  22.0    male   1.0
2   mike   0.0    male   4.0
3      0   0.0       0   0.0
4   jane   0.0  female   0.0
5   lisa  20.0  female   0.0
6  messi  21.0    male   7.0

In [8]:
rank_df.fillna(method='pad')

/var/folders/qc/8xpr08s54_s0v48dxprx9v_00000gn/T/ipykernel_27412/2096487961.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  rank_df.fillna(method='pad')

    name   age  gender  rank
0  steve  20.0    male   2.0
1   john  22.0    male   1.0
2   mike  22.0    male   4.0
3   mike  22.0    male   4.0
4   jane  22.0  female   4.0
5   lisa  20.0  female   4.0
6  messi  21.0    male   7.0

In [9]:
rank_df.fillna(method='bfill')

/var/folders/qc/8xpr08s54_s0v48dxprx9v_00000gn/T/ipykernel_27412/1713328204.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  rank_df.fillna(method='bfill')

    name   age  gender  rank
0  steve  20.0    male   2.0
1   john  22.0    male   1.0
2   mike  20.0    male   4.0
3   jane  20.0  female   7.0
4   jane  20.0  female   7.0
5   lisa  20.0  female   7.0
6  messi  21.0    male   7.0

In [10]:
rank_df.interpolate(method='linear')

/var/folders/qc/8xpr08s54_s0v48dxprx9v_00000gn/T/ipykernel_27412/1596950646.py:1: FutureWarning: DataFrame.interpolate with object dtype is deprecated and will raise in a future version. Call obj.infer_objects(copy=False) before interpolating instead.
  rank_df.interpolate(method='linear')

    name   age  gender  rank
0  steve  20.0    male  2.00
1   john  22.0    male  1.00
2   mike  21.5    male  4.00
3    NaN  21.0     NaN  4.75
4   jane  20.5  female  5.50
5   lisa  20.0  female  6.25
6  messi  21.0    male  7.00

In [11]:
rank_df.dropna()

    name   age gender  rank
0  steve  20.0   male   2.0
1   john  22.0   male   1.0
6  messi  21.0   male   7.0

In [12]:
rank_df.dropna(how='all')

    name   age  gender  rank
0  steve  20.0    male   2.0
1   john  22.0    male   1.0
2   mike   NaN    male   4.0
4   jane   NaN  female   NaN
5   lisa  20.0  female   NaN
6  messi  21.0    male   7.0

In [13]:
rank_df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6]

In [14]:
rank_df.dropna(axis=0)

    name   age gender  rank
0  steve  20.0   male   2.0
1   john  22.0   male   1.0
6  messi  21.0   male   7.0